version: '3.8'

services:
  app:
    # image: USERNAME/IMAGE:latest
    command: gunicorn -w 2 -b 0.0.0.0:5000 web:app
    ports:
      - 5000:5000
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - /root/model-cache:/root/.cache
